services:
  - type: web
    name: atoms-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      # Set the allowed frontend origin (update after frontend deploy)
      - key: FRONTEND_URL
        value: https://atoms-frontend.onrender.com
      # Provide your database connection string in the Render dashboard
      # - key: MONGODB_URI
      #   sync: false
    healthCheckPath: /health

  - type: static
    name: atoms-frontend
    env: static
    rootDir: .
    buildCommand: npm ci && npm run build
    publishPath: dist
    autoDeploy: true
    routes:
      # SPA fallback: rewrite every non-file path to index.html so React Router can handle it
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        # Update to backend URL after it is deployed, e.g. https://atoms-backend.onrender.com/api
        value: https://atoms-backend.onrender.com/api
